name: Build and deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash    
    steps:      
      - run: echo Build
      
  deploy:
      environment: production
      needs: build
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash    
      steps:      
        - run: echo Deploy
      
